// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List products in the BrendSport catalog. Optionally filter by category (shoes, cloth, sport-cloth, sport-shoes).",
  inputSchema: {
    category: z.enum(["shoes", "cloth", "sport-cloth", "sport-shoes"]).optional().describe("Optional category filter"),
    limit: z.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    let q = sb().from("products").select("*").limit(limit);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { products: data }
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.3";
var search_products_default = defineTool2({
  name: "search_products",
  title: "Search products",
  description: "Search BrendSport products by keyword in the product name. Returns matching products.",
  inputSchema: {
    query: z2.string().min(1).describe("Keyword to match in the product name"),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("products").select("*").ilike("name", `%${query}%`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { products: data }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.3";
var get_product_default = defineTool3({
  name: "get_product",
  title: "Get product",
  description: "Retrieve full details of a single BrendSport product by its ID.",
  inputSchema: {
    id: z3.string().uuid().describe("Product UUID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("products").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Product not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_categories_default = defineTool4({
  name: "list_categories",
  title: "List categories",
  description: "List the product categories available in the BrendSport catalog and the sizes each category uses.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const categories = [
      { value: "shoes", label: "Shoes", sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44"] },
      { value: "cloth", label: "Cloth", sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"] },
      { value: "sport-cloth", label: "Sport Cloth", sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"] },
      { value: "sport-shoes", label: "Sport Shoes", sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44"] }
    ];
    void z4;
    return {
      content: [{ type: "text", text: JSON.stringify(categories, null, 2) }],
      structuredContent: { categories }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "brendsport-mcp",
  title: "BrendSport Store",
  version: "0.1.0",
  instructions: "Tools for browsing the BrendSport clothing & shoe catalog. Use `list_categories` to see available product categories, `list_products` to browse products (optionally filtered by category), `search_products` to find products by keyword, and `get_product` to fetch full details of a specific product.",
  tools: [list_products_default, search_products_default, get_product_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
